alias setprompt 'set prompt="%n@%m:%{\e[35m%}$cwd :%{\e[0m%}>"'
setprompt
alias sc 'source ~/.cshrc'
alias g 'gvim'
alias cd 'cd \!* && setprompt ; ls'
alias . 'cd ..'
alias .. 'cd ../..'
alias ... 'cd ../../..'
alias .... 'cd ../../../..'
alias ..... 'cd ../../../../..'
alias ...... 'cd ../../../../../..'
